# Generated by Django 3.2.9 on 2021-11-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='이름')),
                ('description', models.CharField(max_length=128, verbose_name='설명')),
            ],
            options={
                'verbose_name': '샵',
                'verbose_name_plural': '샵',
            },
        ),
    ]
